/*
 * bidding.rs
 *
 * Purpose:
 *     On-chain bid placement and highest bid retrieval.
 *
 *     This module handles all transaction sending and view calls
 *     related to the auction bidding lifecycle.
 *
 *     It does NOT:
 *         - Handle HTTP requests
 *         - Manage provider connections (passed in from main.rs)
 *         - Load contract ABIs at runtime (sol!() macro handles this at compile time)
 *
 *     It is called by:
 *         main.rs    (place_bid called directly from the entry point)
 *
 * System Position:
 *
 *     main.rs  (entry point / orchestration layer)
 *         ↓
 *     bidding.rs  ← THIS FILE (bid transactions + view calls)
 *         ↓
 *     auction_loader.rs  (provider connection)
 *         ↓
 *     Hardhat / Ethereum node
 */

use alloy::{
    network::TransactionBuilder,
    primitives::{Address, U256},
    providers::Provider,
    rpc::types::TransactionRequest,
    sol,
    sol_types::SolCall,
};
use eyre::Result;

// Define the smart contract interface at compile time.
// The sol!() macro takes Solidity function signatures and generates
// typed Rust structs (bidCall, highestBidCall) with ABI encode/decode
// built in. This means invalid call signatures are caught at compile
// time rather than at runtime.
sol! {
    function bid() external payable;
    function highestBid() external view returns (uint256);
}

/// Structured result returned after a successful bid transaction.
///
/// Holds the confirmed transaction hash and the updated highest bid
/// fetched from the contract after the transaction is mined.
#[derive(Debug)]
pub struct BidResult {
    /// Transaction hash of the submitted bid, formatted as a hex string.
    pub tx_hash: String,
    /// Highest bid on the contract after this bid was confirmed, in wei.
    pub highest_bid_wei: U256,
}

/// Place a bid on the auction contract and return the result.
///
/// Sends a payable transaction to the contract's bid() function,
/// waits for the on-chain receipt, then fetches the updated highest bid.
///
/// The provider is generic over P: Provider so this function works with
/// any Alloy provider (HTTP, WebSocket, mock for tests, etc.) without
/// needing to know the concrete type.
///
/// Parameters:
///     provider:         Active Alloy provider for sending transactions.
///     contract_address: On-chain address of the deployed auction contract.
///     bidder:           Address that the transaction will be sent from.
///     bid_amount_wei:   Value to attach to the transaction, in wei.
///
/// Returns:
///     BidResult: Contains the tx hash and the new highest bid after confirmation.
///
/// Errors:
///     Returns Err if the transaction fails, is reverted, or the RPC call errors.
pub async fn place_bid<P>(
    provider: &P,
    contract_address: Address,
    bidder: Address,
    bid_amount_wei: U256,
) -> Result<BidResult>
where
    P: Provider + ?Sized,
{
    // Encode the bid() function signature into raw ABI calldata bytes.
    // bidCall was generated by the sol!() macro above.
    // bid() takes no arguments, so the struct has no fields.
    let calldata = bidCall {}.abi_encode();

    // Build the transaction request with all required fields.
    // .with_value() attaches ETH to the call — required because bid() is payable.
    // The builder pattern lets each field be set independently and clearly.
    let tx = TransactionRequest::default()
        .with_from(bidder)
        .with_to(contract_address)
        .with_value(bid_amount_wei)
        .with_input(calldata);

    // Send the transaction and wait for it to be mined.
    // send_transaction() submits to the mempool and returns a pending tx handle.
    // .get_receipt() waits until the tx is included in a block and returns the receipt.
    // Both steps are async — the thread is free while waiting for the node.
    let receipt = provider.send_transaction(tx).await?.get_receipt().await?;

    // After confirmation, read the updated highest bid from the contract.
    // This is a separate view call — see get_highest_bid() below.
    let highest_bid = get_highest_bid(provider, contract_address).await?;

    Ok(BidResult {
        tx_hash: format!("{:?}", receipt.transaction_hash),
        highest_bid_wei: highest_bid,
    })
}

/// Read the current highest bid from the auction contract.
///
/// This is a view call — it reads state from the contract without
/// sending a transaction or spending gas.
///
/// Parameters:
///     provider:         Active Alloy provider for making RPC calls.
///     contract_address: On-chain address of the deployed auction contract.
///
/// Returns:
///     U256: Current highest bid in wei.
///           U256 is a 256-bit unsigned integer, matching Solidity's uint256.
///
/// Errors:
///     Returns Err if the RPC call fails or the response cannot be decoded.
pub async fn get_highest_bid<P>(
    provider: &P,
    contract_address: Address,
) -> Result<U256>
where
    P: Provider + ?Sized,
{
    // Encode the highestBid() function call into calldata.
    // highestBidCall was generated by the sol!() macro.
    // No arguments needed — highestBid() is a zero-parameter view function.
    let calldata = highestBidCall {}.abi_encode();

    // Build a read-only call request.
    // No .with_from() or .with_value() needed — view calls don't send ETH
    // and don't require a sender address.
    let tx = TransactionRequest::default()
        .with_to(contract_address)
        .with_input(calldata);

    // Execute the view call and receive the raw response bytes from the node.
    // provider.call() does not submit a transaction — it simulates execution
    // and returns the return value directly.
    let response = provider.call(tx).await?;

    // Decode the raw response bytes back into a typed U256.
    // abi_decode_returns() is generated by sol!() and knows the exact
    // return type layout from the Solidity signature.
    let highest_bid = highestBidCall::abi_decode_returns(&response)?;

    Ok(highest_bid)
}